# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
org.gradle.jvmargs=-Xmx4G -Xms1G -XX:+UseParallelGC
org.gradle.daemon=true
org.gradle.debug=false
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

neogradle.subsystems.parchment.minecraftVersion=1.20.2
neogradle.subsystems.parchment.mappingsVersion=2023.12.10
minecraft_version=1.20.2
minecraft_version_range=[1.20.5,)
neo_version=20.2.88
neo_version_range=[20.5,)
loader_version_range=[1,)
